### ISSUE TITLE
http to https forced rerouting

### ISSUE THREAD

**Issue by YukioRivera** [BayTech-CSUMB/What-Can-We-Play-Today#27]
lag when accessing server through browser, might be related to http pinged first then https so we are going to see if we find a way to make https get pinged first

**Comment by TidalWings** [comment]
Work started with 958e02918d11620ac07f768dfa581c5547dc1d82, but needs further work to keep redirects smooth on certain browsers (so far Chromium-based ones).

**Comment by TidalWings** [comment]
Fixed with proper HTTP status message in 7f082b00cd33d3ab7ac3d4adc5fe0cc819a75680
